apiVersion: v1
kind: ConfigMap
metadata:
  name: lightweight-descheduler-config
  namespace: kube-system
data:
  config.yaml: |
    # 轻量级重调度器配置文件
    
    # 基本配置
    interval: "5m"          # 运行间隔
    dryRun: false           # 是否只是模拟运行
    logLevel: "info"        # 日志级别
    
    # 驱逐限制
    limits:
      maxPodsToEvictPerNode: 5
      maxPodsToEvictPerNamespace: 3
      maxPodsToEvictTotal: 20
    
    # 策略配置
    strategies:
      # 失败Pod清理策略
      removeFailedPods:
        enabled: true
        minPodLifetimeSeconds: 300
        excludeOwnerKinds:
          - "Job"
        excludedNamespaces:
          - "kube-system"
          - "kube-public"
          - "kube-node-lease"
      
      # 低节点利用率策略
      lowNodeUtilization:
        enabled: true
        numberOfNodes: 1
        thresholds:
          cpu: 20
          memory: 20
          pods: 20
        targetThresholds:
          cpu: 80
          memory: 80
          pods: 80
      
      # 重复Pod清理策略
      removeDuplicates:
        enabled: false          # 默认关闭，需要时可启用
        excludeOwnerKinds:
          - "DaemonSet"
        excludedNamespaces:
          - "kube-system"
          - "kube-public"
