apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightweight-descheduler
  namespace: kube-system
  labels:
    app: lightweight-descheduler
    version: v1.0.0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lightweight-descheduler
  template:
    metadata:
      labels:
        app: lightweight-descheduler
        version: v1.0.0
    spec:
      serviceAccountName: lightweight-descheduler
      containers:
      - name: lightweight-descheduler
        image: lightweight-descheduler:v1.0.0  # 需要替换为实际的镜像地址
        imagePullPolicy: IfNotPresent
        command:
        - /app/lightweight-descheduler
        args:
        - -config=/etc/descheduler/config.yaml
        - -log-level=2
        volumeMounts:
        - name: config
          mountPath: /etc/descheduler
          readOnly: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep '[l]ightweight-descheduler' || exit 1"
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep '[l]ightweight-descheduler' || exit 1"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
          capabilities:
            drop:
            - ALL
      volumes:
      - name: config
        configMap:
          name: lightweight-descheduler-config
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "CriticalAddonsOnly"
        operator: "Exists"
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      restartPolicy: Always
      priorityClassName: system-cluster-critical
